---
- name: Shutdown server
  hosts: "{{ host }}"
  tasks:
  - name: Shutdown server
    shell: shutdown -h "Ansible shutdown triggered"
    async: 1
    poll: 0
    become: true
    ignore_errors: true
